CONFIG_LOG=y
CONFIG_LED_STRIP=y
CONFIG_LED_STRIP_LOG_LEVEL_DBG=y

CONFIG_I2S=y
CONFIG_WS2812_STRIP_I2S=y
CONFIG_DMA=y

CONFIG_APP_LED_INT_SAMPLE_BRIGHTNESS=75
CONFIG_APP_LED_ENABLE_CUSTOM_BLINK_PATTERN=y